version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: weekly
    reviewers: []
    labels:
      - "dependencies"
      - "nuget"
    target-branch: "main"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    reviewers: []
    labels:
      - "dependencies"
      - "github-actions"
    target-branch: "main"
