<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <ApplicationIcon />
    <OutputType>Exe</OutputType>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <StartupObject>BadDicom.Program</StartupObject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="BadDicom.template.yaml" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="BadDicom.template.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="HIC.DicomTypeTranslation" />
    <PackageReference Include="Vecc.YamlDotNet.Analyzers.StaticGenerator" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SynthDicom\SynthDicom.csproj" />
  </ItemGroup>
</Project>
